<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TurtlePath.Studio.Abstractions\TurtlePath.Studio.Abstractions.csproj" />
    <ProjectReference Include="..\TurtlePath.Studio.Application\TurtlePath.Studio.Application.csproj" />
  </ItemGroup>
</Project>
