using Heroes.Service.Business.Heroes.Models.Requests;
using Heroes.Service.Business.Heroes.Models.Responses;
using Heroes.Service.Domain;
using TurtlePath.Automations.Profiles;

namespace Heroes.Service.Business.Heroes.Automations;

/// <summary>
/// Declares the happy-path handlers generated by TurtlePath for heroes.
/// </summary>
public sealed class HeroAutomationProfile : TurtlePathAutomationProfile
{
    /// <inheritdoc />
    public override void Configure(ITurtlePathAutomationBuilder builder)
    {
        builder.For<Hero>()
            .ToCreate<CreateHeroRequest, HeroResponse>(options => options.Include(hero => hero.Team))
            .ToUpdate<UpdateHeroRequest, HeroResponse>(options => options.Include(hero => hero.Team))
            .ToPatch<DeactivateHeroRequest>();
    }
}
