namespace TurtlePath.Persistence.ValueGenerators
{
    using System;
    using Microsoft.EntityFrameworkCore.ChangeTracking;
    using Microsoft.EntityFrameworkCore.ValueGeneration;

    /// <summary>
    /// Provides a value generator that produces the current UTC date and time for entity properties.
    /// </summary>
    /// <remarks>This generator is typically used for properties that require a timestamp indicating when an
    /// entity was created or last modified. The generated value is consistent across calls within the same operation
    /// and is not considered temporary.</remarks>
    public sealed class UtcNowValueGenerator : ValueGenerator<DateTime>
    {
        /// <summary>
        /// Gets a value indicating whether this member generates temporary values.
        /// </summary>
        /// <remarks>This property always returns <see langword="false"/>, indicating that no temporary
        /// values are generated by this member.</remarks>
        public override bool GeneratesTemporaryValues => false;

        /// <summary>
        /// Gets the next value for the property.
        /// </summary>
        /// <param name="entry">The entity entry for which the value is being generated.</param>
        /// <returns>The current UTC date and time.</returns>
        public override DateTime Next(EntityEntry entry)
            => DateTime.UtcNow;
    }
}
