<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TurtlePath.Testing\TurtlePath.Testing.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.Testing.EntityFrameworkCore\TurtlePath.Testing.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
