<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TurtlePath\TurtlePath.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.Domain\TurtlePath.Domain.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.EntityFrameworkCore\TurtlePath.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.AutoMapper\TurtlePath.AutoMapper.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.FluentValidation\TurtlePath.FluentValidation.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.ExceptionHandling\TurtlePath.ExceptionHandling.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.ExceptionHandling.AspNetCore\TurtlePath.ExceptionHandling.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.ExceptionHandling.Consumers\TurtlePath.ExceptionHandling.Consumers.csproj" />
    <ProjectReference Include="..\..\src\TurtlePath.ExceptionHandling.Workers\TurtlePath.ExceptionHandling.Workers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>


